/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PhotoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "photo";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  gallerySort?: "manual" | "newest";
  reelPhotos?: Array<
    {
      _key: string;
    } & PhotoReference
  >;
  selectedSeries?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  lead?: LocaleText;
  details?: Array<{
    label?: LocaleString;
    value?: LocaleString;
    _type: "detail";
    _key: string;
  }>;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: LocaleString;
  metaDescription?: LocaleText;
};

export type LocaleString = {
  _type: "localeString";
  en?: string;
  bg?: string;
};

export type LocaleText = {
  _type: "localeText";
  en?: string;
  bg?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  lead?: LocaleText;
  text?: LocaleText;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    _type: "image";
  };
  services?: Array<
    {
      _key: string;
    } & LocaleString
  >;
  recognition?: Array<
    {
      _key: string;
    } & LocaleString
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type JournalPost = {
  _id: string;
  _type: "journalPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  category?: LocaleString;
  excerpt?: LocaleText;
  photo?: PhotoReference;
  date?: string;
};

export type Photo = {
  _id: string;
  _type: "photo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: LocaleString;
  caption?: LocaleString;
  primaryCategory?: CategoryReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  takenAt?: string;
  showInGallery?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: LocaleString;
  slug?: Slug;
  description?: LocaleText;
  coverPhoto?: PhotoReference;
  photoOrder?: Array<
    {
      _key: string;
    } & PhotoReference
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PhotoReference
  | CategoryReference
  | SiteSettings
  | ContactPage
  | Seo
  | LocaleString
  | LocaleText
  | SanityImageAssetReference
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | JournalPost
  | Photo
  | Category
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../ivan-marek-portfolio/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    gallerySort,    "reelPhotos": reelPhotos[]->{      _id,      image,      "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),      "caption": select($locale == "bg" => coalesce(caption.bg, caption.en), caption.en),      "lqip": image.asset->metadata.lqip,      "aspectRatio": image.asset->metadata.dimensions.aspectRatio    },    "selectedSeries": selectedSeries[]->{      _id,      "slug": slug.current,      "title": select($locale == "bg" => coalesce(title.bg, title.en), title.en),      "coverPhoto": coverPhoto->{        _id,        image,        "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),        "caption": select($locale == "bg" => coalesce(caption.bg, caption.en), caption.en),        "lqip": image.asset->metadata.lqip,        "aspectRatio": image.asset->metadata.dimensions.aspectRatio      }    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  gallerySort: "manual" | "newest" | null;
  reelPhotos: Array<{
    _id: string;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    alt: string | null;
    caption: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  }> | null;
  selectedSeries: Array<{
    _id: string;
    slug: string | null;
    title: string | null;
    coverPhoto: {
      _id: string;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      alt: string | null;
      caption: string | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
  }> | null;
} | null;

// Source: ../ivan-marek-portfolio/lib/sanity/queries.ts
// Variable: GALLERY_PHOTOS_QUERY
// Query: *[_type == "photo" && showInGallery == true] | order(orderRank asc){    _id,    image,    takenAt,    "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),    "caption": select($locale == "bg" => coalesce(caption.bg, caption.en), caption.en),    "lqip": image.asset->metadata.lqip,    "aspectRatio": image.asset->metadata.dimensions.aspectRatio  }
export type GALLERY_PHOTOS_QUERY_RESULT = Array<{
  _id: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  takenAt: string | null;
  alt: string | null;
  caption: string | null;
  lqip: string | null;
  aspectRatio: number | null;
}>;

// Source: ../ivan-marek-portfolio/lib/sanity/queries.ts
// Variable: CATEGORY_PHOTOS_QUERY
// Query: *[_type == "photo"    && showInGallery == true    && (primaryCategory._ref == $categoryId || $categoryId in categories[]._ref)  ] | order(orderRank asc){    _id,    image,    takenAt,    "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),    "caption": select($locale == "bg" => coalesce(caption.bg, caption.en), caption.en),    "lqip": image.asset->metadata.lqip,    "aspectRatio": image.asset->metadata.dimensions.aspectRatio  }
export type CATEGORY_PHOTOS_QUERY_RESULT = Array<{
  _id: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  takenAt: string | null;
  alt: string | null;
  caption: string | null;
  lqip: string | null;
  aspectRatio: number | null;
}>;

// Source: ../ivan-marek-portfolio/lib/sanity/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(orderRank asc){    _id,    "slug": slug.current,    "title": select($locale == "bg" => coalesce(title.bg, title.en), title.en),    "description": select($locale == "bg" => coalesce(description.bg, description.en), description.en)  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  title: string | null;
  description: string | null;
}>;

// Source: ../ivan-marek-portfolio/lib/sanity/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{    _id,    "slug": slug.current,    "title": select($locale == "bg" => coalesce(title.bg, title.en), title.en),    "description": select($locale == "bg" => coalesce(description.bg, description.en), description.en),    "photoOrder": photoOrder[]._ref  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  slug: string | null;
  title: string | null;
  description: string | null;
  photoOrder: Array<string> | null;
} | null;

// Source: ../ivan-marek-portfolio/lib/sanity/queries.ts
// Variable: CATEGORY_SLUGS_QUERY
// Query: *[_type == "category" && defined(slug.current)].slug.current
export type CATEGORY_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../ivan-marek-portfolio/lib/sanity/queries.ts
// Variable: JOURNAL_POSTS_QUERY
// Query: *[_type == "journalPost"] | order(date desc){    _id,    date,    "title": select($locale == "bg" => coalesce(title.bg, title.en), title.en),    "excerpt": select($locale == "bg" => coalesce(excerpt.bg, excerpt.en), excerpt.en),    "category": select($locale == "bg" => coalesce(category.bg, category.en), category.en),    "photo": photo->{      _id,      image,      "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),      "caption": select($locale == "bg" => coalesce(caption.bg, caption.en), caption.en),      "lqip": image.asset->metadata.lqip,      "aspectRatio": image.asset->metadata.dimensions.aspectRatio    }  }
export type JOURNAL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  date: string | null;
  title: string | null;
  excerpt: string | null;
  category: string | null;
  photo: {
    _id: string;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    alt: string | null;
    caption: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  } | null;
}>;

// Source: ../ivan-marek-portfolio/lib/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0]{    "name": select($locale == "bg" => coalesce(name.bg, name.en), name.en),    "lead": select($locale == "bg" => coalesce(lead.bg, lead.en), lead.en),    "text": select($locale == "bg" => coalesce(text.bg, text.en), text.en),    "portrait": portrait{      ...,      "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),      "lqip": asset->metadata.lqip,      "aspectRatio": asset->metadata.dimensions.aspectRatio    },    "services": services[]{      "value": select($locale == "bg" => coalesce(bg, en), en)    },    "recognition": recognition[]{      "value": select($locale == "bg" => coalesce(bg, en), en)    },    "seo": seo{      "metaTitle": select($locale == "bg" => coalesce(metaTitle.bg, metaTitle.en), metaTitle.en),      "metaDescription": select($locale == "bg" => coalesce(metaDescription.bg, metaDescription.en), metaDescription.en)    }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  name: string | null;
  lead: string | null;
  text: string | null;
  portrait: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
    lqip: string | null;
    aspectRatio: number | null;
  } | null;
  services: Array<{
    value: string | null;
  }> | null;
  recognition: Array<{
    value: string | null;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
  } | null;
} | null;

// Source: ../ivan-marek-portfolio/lib/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage"][0]{    "lead": select($locale == "bg" => coalesce(lead.bg, lead.en), lead.en),    "details": details[]{      _key,      "label": select($locale == "bg" => coalesce(label.bg, label.en), label.en),      "value": select($locale == "bg" => coalesce(value.bg, value.en), value.en)    },    "seo": seo{      "metaTitle": select($locale == "bg" => coalesce(metaTitle.bg, metaTitle.en), metaTitle.en),      "metaDescription": select($locale == "bg" => coalesce(metaDescription.bg, metaDescription.en), metaDescription.en)    }  }
export type CONTACT_PAGE_QUERY_RESULT = {
  lead: string | null;
  details: Array<{
    _key: string;
    label: string | null;
    value: string | null;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    gallerySort,\n    "reelPhotos": reelPhotos[]->{\n      _id,\n      image,\n      "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),\n      "caption": select($locale == "bg" => coalesce(caption.bg, caption.en), caption.en),\n      "lqip": image.asset->metadata.lqip,\n      "aspectRatio": image.asset->metadata.dimensions.aspectRatio\n    },\n    "selectedSeries": selectedSeries[]->{\n      _id,\n      "slug": slug.current,\n      "title": select($locale == "bg" => coalesce(title.bg, title.en), title.en),\n      "coverPhoto": coverPhoto->{\n        _id,\n        image,\n        "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),\n        "caption": select($locale == "bg" => coalesce(caption.bg, caption.en), caption.en),\n        "lqip": image.asset->metadata.lqip,\n        "aspectRatio": image.asset->metadata.dimensions.aspectRatio\n      }\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "photo" && showInGallery == true] | order(orderRank asc){\n    _id,\n    image,\n    takenAt,\n    "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),\n    "caption": select($locale == "bg" => coalesce(caption.bg, caption.en), caption.en),\n    "lqip": image.asset->metadata.lqip,\n    "aspectRatio": image.asset->metadata.dimensions.aspectRatio\n  }\n': GALLERY_PHOTOS_QUERY_RESULT;
    '\n  *[_type == "photo"\n    && showInGallery == true\n    && (primaryCategory._ref == $categoryId || $categoryId in categories[]._ref)\n  ] | order(orderRank asc){\n    _id,\n    image,\n    takenAt,\n    "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),\n    "caption": select($locale == "bg" => coalesce(caption.bg, caption.en), caption.en),\n    "lqip": image.asset->metadata.lqip,\n    "aspectRatio": image.asset->metadata.dimensions.aspectRatio\n  }\n': CATEGORY_PHOTOS_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)] | order(orderRank asc){\n    _id,\n    "slug": slug.current,\n    "title": select($locale == "bg" => coalesce(title.bg, title.en), title.en),\n    "description": select($locale == "bg" => coalesce(description.bg, description.en), description.en)\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0]{\n    _id,\n    "slug": slug.current,\n    "title": select($locale == "bg" => coalesce(title.bg, title.en), title.en),\n    "description": select($locale == "bg" => coalesce(description.bg, description.en), description.en),\n    "photoOrder": photoOrder[]._ref\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)].slug.current\n': CATEGORY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "journalPost"] | order(date desc){\n    _id,\n    date,\n    "title": select($locale == "bg" => coalesce(title.bg, title.en), title.en),\n    "excerpt": select($locale == "bg" => coalesce(excerpt.bg, excerpt.en), excerpt.en),\n    "category": select($locale == "bg" => coalesce(category.bg, category.en), category.en),\n    "photo": photo->{\n      _id,\n      image,\n      "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),\n      "caption": select($locale == "bg" => coalesce(caption.bg, caption.en), caption.en),\n      "lqip": image.asset->metadata.lqip,\n      "aspectRatio": image.asset->metadata.dimensions.aspectRatio\n    }\n  }\n': JOURNAL_POSTS_QUERY_RESULT;
    '\n  *[_type == "aboutPage"][0]{\n    "name": select($locale == "bg" => coalesce(name.bg, name.en), name.en),\n    "lead": select($locale == "bg" => coalesce(lead.bg, lead.en), lead.en),\n    "text": select($locale == "bg" => coalesce(text.bg, text.en), text.en),\n    "portrait": portrait{\n      ...,\n      "alt": select($locale == "bg" => coalesce(alt.bg, alt.en), alt.en),\n      "lqip": asset->metadata.lqip,\n      "aspectRatio": asset->metadata.dimensions.aspectRatio\n    },\n    "services": services[]{\n      "value": select($locale == "bg" => coalesce(bg, en), en)\n    },\n    "recognition": recognition[]{\n      "value": select($locale == "bg" => coalesce(bg, en), en)\n    },\n    "seo": seo{\n      "metaTitle": select($locale == "bg" => coalesce(metaTitle.bg, metaTitle.en), metaTitle.en),\n      "metaDescription": select($locale == "bg" => coalesce(metaDescription.bg, metaDescription.en), metaDescription.en)\n    }\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "contactPage"][0]{\n    "lead": select($locale == "bg" => coalesce(lead.bg, lead.en), lead.en),\n    "details": details[]{\n      _key,\n      "label": select($locale == "bg" => coalesce(label.bg, label.en), label.en),\n      "value": select($locale == "bg" => coalesce(value.bg, value.en), value.en)\n    },\n    "seo": seo{\n      "metaTitle": select($locale == "bg" => coalesce(metaTitle.bg, metaTitle.en), metaTitle.en),\n      "metaDescription": select($locale == "bg" => coalesce(metaDescription.bg, metaDescription.en), metaDescription.en)\n    }\n  }\n': CONTACT_PAGE_QUERY_RESULT;
  }
}
